### ISSUE TITLE
SVGs don't render correctly on GitHub

### ISSUE THREAD

**Issue by adius** [marionebl/svg-term-cli#25] opened 2018-01-21 14:24 UTC
https://github.com/adius/svg-term-bug

This is a strange bug. The images look OK in every program I checked them, but not on GitHub.

I think the problem has  either to do with GitHub sanitizing the SVGs (sanitize=true) or that they are loaded in an image tag. Altough the normal and the sanitized SVG code looks OK.

I think I remember that SVGs in images are treated as XML and otherwise as HTML and you're using some weird <svg> in <svg> code, which might be only allowed in HTML. But on the other hand the images in your projects seem to be OK .... 😩

**Comment by marionebl** [comment] 2018-01-21 14:28
This is related to GitHub sanitizing SVG files. You can work around this by using rawgit:

`https://cdn.rawgit.com/adius/svg-term-bug/afa571c1/bug.svg`

![](https://cdn.rawgit.com/adius/svg-term-bug/afa571c1/bug.svg)

This is a duplicate of #5, let's move any further discussion there.

**Closed by marionebl** 2018-01-21 14:28 UTC

**Comment by adius** [comment] 2018-01-21 14:35
Oh, I see, thanks. Should have searched more properly for existing issues 🙈
